---
- name: Load launchd agent
  command: launchctl load {{ home }}/Library/LaunchAgents/powerline.plist
  notify: start powerline
- name: start powerline
  command: launchctl start powerline

- name: Enable systemd agent
  systemd:
    user: true
    enabled: true
    state: started
    name: powerline.service
