---
- name: Install Fish
  package: name=fish state={{ install_state }}
  become: "{{ need_sudo }}"
- name: Fish Command Prompt
  file:
    path: "{{ home }}/.config/fish/functions"
    owner: "{{ ansible_user }}"
    state: directory
    recurse: true
- name: Bubble Text function
  copy:
    owner: "{{ ansible_user }}"
    src: bubble_text.fish
    dest: "{{ home }}/.config/fish/functions/bubble_text.fish"
- name: Fish Command Prompt
  copy:
    owner: "{{ ansible_user }}"
    src: fish_prompt.fish
    dest: "{{ home }}/.config/fish/functions/fish_prompt.fish"
