---
- name: Install Fish
  package: name=fish state={{ install_state }}
  become: "{{ need_sudo }}"
- name: Fish Base dir
  file:
    path: "{{ home }}/.config/fish"
    owner: "{{ ansible_user }}"
    state: directory
    recurse: true
- name: Fish Config File
  template:
    owner: "{{ ansible_user }}"
    mode: "0644"
    src: config.fish.j2
    dest: "{{ home }}/.config/fish/config.fish"
- name: Fish Functions Dir
  file:
    path: "{{ home }}/.config/fish/functions"
    owner: "{{ ansible_user }}"
    state: directory
    recurse: true
- name: Fish Color Schemes Yaml
  copy:
    owner: "{{ ansible_user }}"
    mode: "0644"
    src: color_schemes.yaml
    dest: "{{ home }}/.config/fish/color_schemes.yaml"
- name: Fish Functions
  copy:
    owner: "{{ ansible_user }}"
    mode: "0644"
    src: "{{ item }}.fish"
    dest: "{{ home }}/.config/fish/functions/{{ item }}.fish"
  loop:
    - bubble_text
    - fish_mode_prompt
    - fish_prompt
    - genpass
    - list_instances
    - random_color_scheme
