---
- name: Install Fish
  ansible.builtin.package:
    name: fish
    state: "{{ install_state }}"
  become: "{{ need_sudo }}"

- name: Fish Base dir
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/fish"
    owner: "{{ ansible_user_id }}"
    state: directory
    recurse: true
  become: false

- name: Fish Config File
  ansible.builtin.template:
    owner: "{{ ansible_user_id }}"
    mode: "0644"
    src: config.fish.j2
    dest: "{{ ansible_user_dir }}/.config/fish/config.fish"
  become: false

- name: Fish Functions Dir
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/fish/functions"
    owner: "{{ ansible_user_id }}"
    state: directory
    recurse: true
  become: false

- name: Fish Color Schemes Yaml
  ansible.builtin.copy:
    owner: "{{ ansible_user_id }}"
    mode: "0644"
    src: color_schemes.yaml
    dest: "{{ ansible_user_dir }}/.config/fish/color_schemes.yaml"
  become: false

- name: Fish Prompt custom
  ansible.builtin.copy:
    owner: "{{ ansible_user_id }}"
    mode: "0644"
    src: "{{ item }}.fish"
    dest: "{{ ansible_user_dir }}/.config/fish/functions/{{ item }}.fish"
  become: false
  when: not fish['starship']
  loop:
    - fish_mode_prompt
    - fish_prompt

- name: Include Starship
  ansible.builtin.include_role:
    name: starship
  when: fish['starship']

- name: Fish Prompt starship
  ansible.builtin.copy:
    owner: "{{ ansible_user_id }}"
    mode: "0644"
    dest: "{{ ansible_user_dir }}/.config/fish/functions/fish_prompt.fish"
    content: "source (/usr/bin/starship init fish --print-full-init | psub)\n"
  become: false
  when: fish['starship']

- name: Fish Functions
  ansible.builtin.copy:
    owner: "{{ ansible_user_id }}"
    mode: "0644"
    src: "{{ item }}.fish"
    dest: "{{ ansible_user_dir }}/.config/fish/functions/{{ item }}.fish"
  become: false
  loop:
    - bubble_text
    - genpass
    - list_instances
    - list_snapshots
    - random_color_scheme
    - upgrade
    - wordpress_server

- name: Conf.d dir
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.fish/conf.d"
    owner: "{{ ansible_user_id }}"
    state: directory
    mode: "0755"
    recurse: true
  become: false

- name: SSH_AUTH_SOCK file
  ansible.builtin.copy:
    owner: "{{ ansible_user_id }}"
    dest: "{{ ansible_user_dir }}/.fish/conf.d/ssh_auth_sock.fish"
    content: set -gx SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"\n
    force: false
    mode: "0644"
  become: false
