---
- name: Install powerline
  pip: name=powerline-status state=latest
  when: ansible_distribution != "Gentoo"
- name: Install powerline on Gentoo
  pip: name=powerline-status state=latest extra_args='--user'
  when: ansible_distribution == "Gentoo"
- name: Create Launch Agents Dir
  file: path={{ home }}/Library/LaunchAgents state=directory owner=kyle_leaders
  when: ansible_distribution == "MacOSX"
- name: Add Powerline Launch Agent
  template:
    src: powerline.plist.j2
    dest: "{{ home }}/Library/LaunchAgents/powerline.plist"
    owner: kyle_leaders
  when: ansible_distribution == "MacOSX"
  notify:
    - Load launchd agent
