---
- name: Install powerline
  pip: name=powerline-status state=latest
  when: ansible_distribution == "MacOSX"

- name: Install powerline
  pip: name=powerline-status state=installed
  when: ansible_distribution == "ArchLinux"
  become: "{{ need_sudo }}"

- name: Install powerline on Gentoo
  pip: name=powerline-status state=latest extra_args='--user'
  when: ansible_distribution == "Gentoo"

- name: Create Launch Agents Dir
  file:
    path: "{{ home }}/Library/LaunchAgents"
    state: directory
    owner: "{{ ansible_user_id }}"
  when: ansible_service_mgr == "launchd"

- name: Create Launch Agents Dir
  file:
    path: "{{ home }}/.config/systemd"
    state: directory
    owner: "{{ ansible_user_id }}"
  when: ansible_service_mgr == "systemd"

- name: Create Launch Agents Dir
  file:
    path: "{{ home }}/.config/systemd/user"
    state: directory
    owner: "{{ ansible_user_id }}"
  when: ansible_service_mgr == "systemd"

- name: Add Powerline Launch Agent
  template:
    src: powerline.plist.j2
    dest: "{{ home }}/Library/LaunchAgents/powerline.plist"
    owner: kyle_leaders
  when: ansible_distribution == "MacOSX"
  notify:
    - Load launchd agent

- name: Add Powerline Systemd Agent
  template:
    src: powerline.service.j2
    dest: "{{ home }}/.config/systemd/user/powerline.service"
    owner: kyle
  when: ansible_service_mgr == "systemd"
  notify:
    - Enable systemd agent
