---
- name: "Set install_state"
  ansible.builtin.set_fact:
    install_state: latest

- name: "Set install_state: Gentoo"
  ansible.builtin.set_fact:
    install_state: installed
  when: ansible_distribution == "Gentoo"

- name: "Set need_sudo: Linux"
  ansible.builtin.set_fact:
    need_sudo: true

- name: "Set need_sudo: Mac"
  ansible.builtin.set_fact:
    need_sudo: false
  when: ansible_distribution == "MacOSX"
