---
- name: Install nodejs
  ansible.builtin.package:
    name: nodejs
    state: "{{ install_state }}"
  become: "{{ need_sudo }}"

- name: Install npm
  ansible.builtin.package:
    name: npm
    state: "{{ install_state }}"
  become: "{{ need_sudo }}"
  when: ansible_distribution != 'Gentoo'
