# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
---
- name: Install nushell
  ansible.builtin.package:
    name: nushell
    state: present
  become: "{{ need_sudo }}"

- name: Install starship
  ansible.builtin.package:
    name: starship
    state: present
  become: "{{ need_sudo }}"

- name: Setup starship
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/starship.toml"
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    src: starship.toml
  become: false

- name: Setup config (linux)
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/nushell/{{ item }}"
    mode: "0644"
    src: "{{ item }}"
  with_items:
    - config.nu
    - env.nu
  when: ansible_system == "Linux"
  become: false

- name: Setup config (mac)
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/Library/Application Support/nushell/{{ item }}"
    mode: "0644"
    src: "{{ item }}"
  with_items:
    - config.nu
    - env.nu
  when: ansible_system == "Darwin"
  become: false
