---
- name: Install git
  ansible.builtin.package:
    name: git
    state: "{{ install_state }}"
  become: "{{ need_sudo }}"

- name: Gitconfig
  ansible.builtin.copy:
    src: gitconfig
    dest: "{{ ansible_user_dir }}/.gitconfig"
    owner: "{{ ansible_user_id }}"
    mode: "0644"
    force: false
