---
- name: Install git
  package: name=git state={{ install_state }}
  become: "{{ need_sudo }}"
- name: gitconfig
  copy:
    src: gitconfig
    dest: "{{ lookup('env','HOME') }}/.gitconfig"
    owner: "{{ ansible_user_id }}"
    mode: "0644"
