---
- name: "Install git"
  package: name=git state=latest
  when: 'ansible_distribution != "Gentoo"'
- name: "Install git"
  package: name=git state=installed
  when: 'ansible_distribution == "Gentoo"'
- name: gitconfig
  copy:
    src: gitconfig
    dest: "{{ lookup('env','HOME') }}/.gitconfig"
    owner: "{{ ansible_user_id }}"
    mode: "0644"
