---
- name: Install Go
  package: name=golang state=present
  when: ansible_distribution == "MacOSX"
- name: Install Go
  package: name=go state=present
  when: 'ansible_distribution != "MacOSX"'
- name: Setup GOPATH
  file: path={{ home }}/Documents/go state=directory owner=kyle_leaders
  when: ansible_distribution == "MacOSX"
- name: Setup GOPATH
  file: path={{ home }}/Documents/go state=directory owner=kyle
  when: 'ansible_distribution != "MacOSX"'
