---
- name: Install tmux
  ansible.builtin.package:
    name: tmux
    state: present
  become: "{{ need_sudo }}"

- name: Configure tmux
  ansible.builtin.template:
    src: tmux.conf.j2
    mode: "0640"
    dest: "{{ ansible_user_dir }}/.tmux.conf"
  become: false

- name: Add tmux dir
  ansible.builtin.file:
    state: directory
    dest: "{{ ansible_user_dir }}/.tmux"
    mode: "0755"
    owner: "{{ ansible_user_id }}"
  become: false

- name: Add tmux plugin dir
  ansible.builtin.file:
    state: directory
    dest: "{{ ansible_user_dir }}/.tmux/plugins"
    mode: "0755"
    owner: "{{ ansible_user_id }}"
  become: false

- name: Add tmux pane file
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.tmux/base.conf"
    mode: "0644"
    src: base.conf
    owner: "{{ ansible_user_id }}"
  become: false

- name: Install TPM
  ansible.builtin.git: # noqa: latest
    dest: "{{ ansible_user_dir }}/.tmux/plugins/tpm"
    clone: true
    update: false
    repo: https://github.com/tmux-plugins/tpm.git
  become: false
