---
- name: Install vim
  ansible.builtin.package:
    name: vim
    state: "{{ install_state }}"
  become: "{{ need_sudo }}"
  when: ansible_distribution != "MacOSX"

- name: Create vimrc
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.vimrc"
    src: "{{ neovim_dir }}/init.vim"
    owner: "{{ ansible_user_id }}"
    state: link
  become: false

- name: Create gvimrc
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.gvimrc"
    content: "set guifont=Hack\\ Nerd\\ Font:h12\n"
    owner: "{{ ansible_user_id }}"
    mode: "0644"
  become: false
