---
- name: install vim
  package: "name=vim state={{ install_state }}"
  become: "{{ need_sudo }}"

- name: create vimrc
  file:
    path: "{{ home }}/.vimrc"
    src: "{{ neovim_dir }}/init.vim"
    owner: "{{ ansible_user_id }}"
    state: link

- name: Create gvimrc
  copy:
    dest: "{{ home }}/.gvimrc"
    content: "set guifont=Hack\\ Nerd\\ Font:h12\n"
    owner: "{{ ansible_user_id }}"
    mode: "0644"
