---
- name: Create alacritty config dir
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/alacritty"
    owner: "{{ ansible_user_id }}"
    mode: "0755"
    state: directory
  become: false
- name: Create alacritty.yml
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/alacritty/alacritty.yml"
    src: alacritty.yml
    mode: "0755"
    owner: "{{ ansible_user_id }}"
  become: false
