---
- name: create alacritty config dir
  file:
    path: "{{ home }}/.config/alacritty"
    owner: "{{ ansible_user_id }}"
    state: directory
- name: create alacritty.yml
  copy:
    dest: "{{ home }}/.config/alacritty/alacritty.yml"
    src: alacritty.yml
    owner: "{{ ansible_user_id }}"
    state: present
