---
- name: install mercurial
  package: name=mercurial state={{ install_state }}
  become: "{{ need_sudo }}"
- name: install hglib
  pip: name=python-hglib state=latest executable=pip3
  when: ansible_distribution == "MacOSX"
- name: install hglib
  package: name=python-hglib state={{ install_state }}
  when: ansible_distribution != "MacOSX"
  become: "{{ need_sudo }}"
