---
- name: install language server npm modules
  npm:
    name: "{{ item }}"
    state: latest
    global: true
  become: "{{ need_sudo }}"
  with_items:
    - '@volar/vue-language-server'
    - intelephense
    - javascript-typescript-langserver
    - vscode-json-languageserver
    - vscode-languageserver
    - yaml-language-server

- name: install solargraph
  gem:
    name: solargraph
    state: latest
  when: false

- name: Install language server pip modules
  pip:
    name:
      - python-lsp-server[all]
    state: latest
    executable: pip3
    extra_args: --user
  become: false
  when: ansible_distribution != "Gentoo"

- name: LSPs for Gentoo
  package:
    name:
      - python-lsp-server
    state: installed
  become: true
  when: ansible_distribution == "Gentoo"

- name: Install go language server
  ansible.builtin.command:
    cmd: go install golang.org/x/tools/gopls@latest
    creates: "{{ home }}/go/bin/gopls"

- name: lsp configuration file
  copy:
    dest: "{{ neovim_dir }}/lsp_settings.json"
    owner: "{{ ansible_user_id }}"
    src: lsp_settings.json

- name: Deno
  ansible.builtin.command:
    cmd: cargo install --locked deno
    creates: "{{ home }}/.cargo/bin/deno"
  tags: [deno]
