---
- name: Install language server npm modules
  community.general.npm:
    name: "{{ item }}"
    state: present
    global: true
  become: false
  with_items:
    - "@volar/vue-language-server"
    - intelephense
    - yaml-language-server
    - vscode-langservers-extracted

- name: Install solargraph
  community.general.gem:
    name: solargraph
    state: latest
  when: false

- name: Install ruby-lsp
  community.general.gem:
    name: ruby-lsp
    state: latest
  when: false

- name: Install language server pip modules
  ansible.builtin.pip:
    name:
      - python-lsp-server[all]
    state: present
    executable: pip3
    extra_args: --user
  become: false
  when: ansible_distribution != "Gentoo"

- name: LSPs for Gentoo
  ansible.builtin.package:
    name:
      - python-lsp-server
    state: installed
  become: true
  when: ansible_distribution == "Gentoo"

- name: Install go language server
  ansible.builtin.command:
    cmd: go install golang.org/x/tools/gopls@latest
    creates: "{{ ansible_user_dir }}/go/bin/gopls"
  become: false

- name: Lsp configuration file
  ansible.builtin.copy:
    dest: "{{ neovim_dir }}/lsp_settings.json"
    owner: "{{ ansible_user_id }}"
    mode: "0644"
    src: lsp_settings.json
  become: false

- name: Deno
  ansible.builtin.command:
    cmd: cargo install --locked deno
    creates: "{{ ansible_user_dir }}/.cargo/bin/deno"
  tags: [deno]
  become: false
