---
- name: install language server npm modules
  npm:
    name: "{{ item }}"
    state: latest
    global: true
  become: "{{ need_sudo }}"
  with_items:
    - yaml-language-server
    - vscode-json-languageserver
    - vscode-languageserver
    - javascript-typescript-langserver
    - intelephense

- name: install ruby language server
  gem:
    name: solargraph
    state: latest
  when: false

- name: Install language server pip modules
  pip:
    name:
      - python-lsp-server[all]
    state: latest
    executable: pip3
    extra_args: --user

- name: Install go language server
  ansible.builtin.command:
    cmd: go install golang.org/x/tools/gopls@latest
    creates: "{{ home }}/go/bin/gopls"

- name: lsp configuration file
  copy:
    dest: "{{ neovim_dir }}/lsp_settings.json"
    src: lsp_settings.json
    owner: "{{ ansible_user_id }}"
