---
- name: Setup init.lua
  ansible.builtin.copy:
    dest: "{{ neovim_dir }}/init.lua"
    src: init.lua
    owner: "{{ ansible_user_id }}"
    mode: "0644"
  become: false

- name: Setup modules dir
  ansible.builtin.file:
    dest: "{{ neovim_dir }}/lua"
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: "0755"
  become: false

- name: Setup extra lua files
  ansible.builtin.copy:
    dest: "{{ neovim_dir }}/lua/{{ item }}"
    src: "{{ item }}"
    owner: "{{ ansible_user_id }}"
    mode: "0644"
  with_items:
    - cmp_config.lua
    - colorscheme.lua
    - feline_ibhagwan.lua
    - lsp.lua
    - lspkind_icons.lua
    - plugins.lua
    - tabnine_config.lua
    - treesitter.lua
    - which.lua
  become: false

- name: Remove init.vim
  ansible.builtin.file:
    dest: "{{ neovim_dir }}/init.vim"
    state: absent
  become: false
