---
- name: Get python3 location
  ansible.builtin.shell: if test -f /usr/local/bin/python3; then echo /usr/local/bin/python3; else which python3; fi
  register: python_bin
  changed_when: python_bin.rc != 0
  when: python_bin is undefined
  become: false

- name: Neovim ppa
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/unstable
  when: ansible_pkg_mgr == 'apt'
  become: true

- name: Install neovim
  ansible.builtin.package: # noqa: latest
    name: neovim
    state: "{{ install_state }}"
  become: "{{ need_sudo }}"

- name: Install ripgrep
  ansible.builtin.package:
    name: ripgrep
    state: "{{ install_state }}"
  become: "{{ need_sudo }}"
  when: ansible_distribution != "Ubuntu"

- name: Install powerline fonts
  ansible.builtin.package:
    name: fonts-powerline
    state: "{{ install_state }}"
  become: "{{ need_sudo }}"
  when: ansible_distribution == "Ubuntu"

- name: Neovim config dir
  ansible.builtin.file:
    dest: "{{ neovim_dir }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: "0755"
  become: false

- name: GUI init file
  ansible.builtin.copy:
    dest: "{{ neovim_dir }}/ginit.vim"
    src: ginit.vim
    owner: "{{ ansible_user_id }}"
    mode: "0644"
  become: false

- name: Language Servers
  ansible.builtin.include_tasks:
    file: language_servers.yml
  tags:
    - language_servers

- name: Neovim LUA Config
  ansible.builtin.include_tasks:
    file: lua.yml
  tags:
    - lua
