---
- name: neovim ppa
  apt_repository: repo='ppa:neovim-ppa/unstable'
  when: ansible_pkg_mgr == 'apt'
  become: true

- name: install neovim
  package: name=neovim state={{ install_state }}
  become: "{{ need_sudo }}"

- name: install neovim clients
  package: name=neovim-{{ item }}-client state={{ install_state }}
  when: 'ansible_distribution == "Gentoo"'
  become: "{{ need_sudo }}"
  with_items:
    - ruby
    - python

- name: install ripgrep
  package: name=ripgrep state={{ install_state }}
  become: "{{ need_sudo }}"
  when: 'ansible_distribution != "Ubuntu"'

- name: install neovim pip module
  pip: name=neovim state=latest executable=pip3
  when: 'ansible_distribution == "MacOSX"'

- name: neovim config dir
  file:
    dest: "{{ neovim_dir }}"
    state: directory
    owner: "{{ansible_user_id}}"
    mode: 0755

- name: neovim init.vim
  template:
    dest: "{{ neovim_dir }}/init.vim"
    src: init.vim.j2
    owner: "{{ansible_user_id}}"
    mode: 0644
