---
- name: Get python3 location
  shell: if test -f /usr/local/bin/python3; then echo /usr/local/bin/python3; else which python3; fi
  register: python_bin

- name: neovim ppa
  apt_repository:
    repo: ppa:neovim-ppa/unstable
  when: ansible_pkg_mgr == 'apt'
  become: true

- name: install neovim
  package:
    name: neovim
    state: "{{ install_state }}"
  become: "{{ need_sudo }}"

- name: install ripgrep
  package:
    name: ripgrep
    state: "{{ install_state }}"
  become: "{{ need_sudo }}"
  when: ansible_distribution != "Ubuntu"

- name: Install powerline fonts
  package:
    name: fonts-powerline
    state: "{{ install_state }}"
  become: "{{ need_sudo }}"
  when: ansible_distribution == "Ubuntu"

- name: install neovim pip module
  pip:
    name: neovim
    state: latest
    executable: pip3
  when: ansible_distribution == "MacOSX"

- name: neovim config dir
  file:
    dest: "{{ neovim_dir }}"
    state: directory
    owner: "{{ansible_user_id}}"
    mode: 0755

- name: GUI init file
  copy:
    dest: "{{ neovim_dir }}/ginit.vim"
    src: ginit.vim
    owner: "{{ansible_user_id}}"
    mode: 0644

- name: Language Servers
  include_tasks:
    file: language_servers.yml
  tags:
    - language_servers

- name: Neovim LUA Config
  include_tasks:
    file: lua.yml
  tags:
    - lua
