---
- name: Install ruby
  ansible.builtin.package:
    name: ruby
    state: "{{ install_state }}"
  become: "{{ need_sudo }}"
- name: Install bundler
  ansible.builtin.package:
    name: ruby-bundler
    state: "{{ install_state }}"
  become: "{{ need_sudo }}"
  when: ansible_distribution == "Ubuntu"
- name: Install ruby-dev
  ansible.builtin.package:
    name: ruby-dev
    state: "{{ install_state }}"
  become: "{{ need_sudo }}"
  when: ansible_distribution == "Ubuntu"
